---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

    driver:
      vagrantfile_erb: Vagrantfile.erb


suites:
  - name: default
    customize:
        memory: 3072

    run_list:
      - recipe[my-lamp::default]

    attributes:
